# Generated by Django 5.2.3 on 2025-07-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_admin_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='shift',
            field=models.CharField(max_length=20),
        ),
    ]
