# Generated by Django 5.2.3 on 2025-07-15 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_trainer_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expireingDate',
            field=models.CharField(default=datetime.date(2025, 7, 31), max_length=20),
            preserve_default=False,
        ),
    ]
